---
title: "McNelly ADA Midterm"
author: "Sam McNelly"
date: "2022-10-13"
output:
  word_document: default
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
#Load commonly used libraries

library(tidyverse, ggplot2)

knitr::opts_chunk$set(echo = TRUE)
```


Part a: Import data
```{r}
#import data from Dr. Johnson's github account (went to the web address provided in the assignment, clicked on "titanic", and then copied the address for the raw data)

titanic<-read.csv("https://raw.githubusercontent.com/kijohnson/Data/main/titanic.csv")
```

Part b: Determine median age by passenger class using titanic data
```{r}
#First, let's check the classes of the two variables in question. 
class(titanic$Pclass)
class(titanic$Age)

#Age is numeric (what we want), but Pclass is integer, and it will be easier for us if it's a factor. Let's change Pclass to a factor variable (will create a new variable so as not to overwrite the original data). 

titanic$Pclass.factor<-as.factor(titanic$Pclass)

#Let's check again to make sure that did what we wanted.

class(titanic$Pclass.factor)
#It's a factor! Hurrah!

#Now let's find the median of passenger age according to their class. I did this in two ways, so as to double check my code. First:

with(titanic, tapply(Age, Pclass.factor, median))

#This shows that the median age of first class passengers was 38.5, second class passengers was 29, and for 3rd class passengers, median age was 24. To double check, I also found median this way:

aggregate(titanic$Age~titanic$Pclass.factor, FUN=median)
#This showed the same results as above! Intuitively, this also makes sense that passengers who were older (and potentially more likely to be wealthy) would be in first class, while younger (and likely poorer) passengers would be in 2nd and 3rd class. 

```


Part c: create a plot that shows the median, spread, and outliers of passenger age according to passenger class.
```{r}
#All signs in this question point toward us creating a boxplot! Let's do it, and assign our boxplot to an object called agebox. 


agebox<-ggplot(data=titanic) + 
  geom_boxplot(mapping = aes(x=Pclass.factor, y=Age)) +
  xlab("Passenger Class") +
  ylab("Passenger Age")

#Let's look at our new boxplot
agebox

#From the boxplot, we can see that for first class passengers, the median age was about 38, with the youngest passenger being about 1, and the oldest being 80 (this value is an outlier). For second class passengers, the median age was about 34, with some passengers being less than one and up to 70 years old (both outliers). Finally, for third class passengers, the median age was about 24, with outlier values of passengers being less than one year old, and up to about 75 years of age. 

```

